apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/label: "eks-agent"
spec:
  serviceAccountName: jenkins
  restartPolicy: Never
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"

    - name: tools
      image: bitnami/kubectl:latest
      command: ['cat']
      tty: true
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
