name: 'EKS-Creation-Using-Terraform'
#ON is defined how workflow will be run using manually or by simple push
#For mauanl run we need to defaine workflow_dispatch for auto re can define like 
#on:
# push: master or pull_request: 
on:
  workflow_dispatch:
    inputs:  # define which env we want to run it
      tfvars_file:
        description: 'Path to the .tfvars file'
        required: true
        default: 'dev.tfvars'
      action:
        type: choice # make choice as per user 
        description: 'Terraform Action'
        options:
          - plan
          - apply
          - destroy
        required: true
        default: 'apply'

env:  # Define env which region depoyment should be done and provide access and secret keys 
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.action }}
    runs-on: ubuntu-latest # github runs on this 
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: eks # Define directory here 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3
          terraform_wrapper: true

      # Optional: Enable caching to speed up init
      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            .terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -diff

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: |
          terraform plan -var-file=${{ github.event.inputs.tfvars_file }} -input=false

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          terraform apply -auto-approve -var-file=${{ github.event.inputs.tfvars_file }} -input=false

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          terraform destroy -auto-approve -var-file=${{ github.event.inputs.tfvars_file }} -input=false
